In [22]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

In [19]:
iris=datasets.load_iris()
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2)

In [20]:
clf= LinearRegression()
cross_val_score(clf,x_train,y_train)

array([ 0.92747917,  0.90494651,  0.93666348])

In [21]:
cross_val_score(clf,iris.data,iris.target)

array([ 0.,  0.,  0.])

In [23]:
cross_val_score(clf,iris.data,iris.target,cv=KFold(3,True,0))

array([ 0.90335825,  0.92525985,  0.94159336])