In [6]:

fibo=[0,1,1]
even=[0]
def gene():
  for i in range(2,10):
    fibo.append(fibo[i-1]+fibo[i-2])
    if(fibo[i] % 2 ==0):
      even.append(fibo[i])
gene()
n=int(input())
sum=0
for i in range(len(even)):
  if(even[i]<=n):
    sum+=even[i]
  else:
    break
print(sum)

10
8


In [70]:
import numpy as np
import matplotlib.pyplot as mp
# a=np.array([1,2,5,9])
a=np.array([ [1,1,0,1],[1,2,2,2] ])
print(a.dtype)
#print(a.mean())
#a=((a-a.mean()))**2
#print(a.dtype)
print(a.shape)
#print(a[1][1])
type(a)
print(a)
print(np.ndim(a))
#mp.plot(a)
#mp.show()
print(a[:2,1:3])

int32
(2, 4)
[[1 1 0 1]
 [1 2 2 2]]
2
[[1 0]
 [2 2]]
