In [1]:
import cifar10
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from numpy import array
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import ensemble

In [2]:
cifar10.data_path = "data/CIFAR-10/"

In [3]:
cifar10.maybe_download_and_extract()

Data has apparently already been downloaded and unpacked.


In [4]:
class_names = cifar10.load_class_names()
class_names

Loading data: data/CIFAR-10/cifar-10-batches-py/batches.meta


['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [6]:
images_train, cls_train, labels_train = cifar10.load_training_data()
images_test, cls_test, labels_test = cifar10.load_test_data()

Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_1
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_2
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_3
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_4
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_5
Loading data: data/CIFAR-10/cifar-10-batches-py/test_batch


In [11]:
images_train_new=images_train.reshape(50000,1024,3)

(50000, 1024, 3)


In [12]:
x_train=labels_train
y_train=cls_train

(50000, 10)
(50000,)


In [ ]:
x_test=labels_test
y_test=cls_test

In [15]:
pca_cifar_train=PCA()
pca_cifar_train.fit(x_train)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [16]:
k=0
total=0
while total<0.99:
    total=total+pca_cifar_train.explained_variance_ratio_[k]
    k=k+1
k    

9

In [ ]:
pca_cifar_train_new=PCA(n_components=k,whiten=True)
x_transformed_train=pca_cifar_train_new.fit_transform(x_train)

In [ ]:
x_transformed_test=pca_cifar_train_new.transform(x_test)

In [19]:
x_train_pca=x_transformed_train
x_test_pca=x_transformed_test

In [20]:
rfc=ensemble.RandomForestClassifier()
rfc.fit(x_train_pca,y_train)
y_pred=rfc.predict(x_test_pca)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1000
          1       1.00      1.00      1.00      1000
          2       1.00      1.00      1.00      1000
          3       1.00      1.00      1.00      1000
          4       1.00      1.00      1.00      1000
          5       1.00      1.00      1.00      1000
          6       1.00      1.00      1.00      1000
          7       1.00      1.00      1.00      1000
          8       1.00      1.00      1.00      1000
          9       1.00      1.00      1.00      1000

avg / total       1.00      1.00      1.00     10000

[[1000    0    0    0    0    0    0    0    0    0]
 [   0 1000    0    0    0    0    0    0    0    0]
 [   0    0 1000    0    0    0    0    0    0    0]
 [   0    0    0 1000    0    0    0    0    0    0]
 [   0    0    0    0 1000    0    0    0    0    0]
 [   0    0    0    0    0 1000    0    0    0    0]
 [   0    0    0    0    0    0 1000    0  

In [ ]:
y_pred_cl=[0 for i in range(y_pred.shape[0])]
for i in range(y_pred.shape[0]):
    y_pred_cl[i]=class_names[y_pred[i]]

In [27]:
np.savetxt('ff.csv',array(y_pred_cl),fmt="%s")